// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCbZTDWpB-WM2nOC1nk27TULQkpf8pdug',
    appId: '1:6732882554:web:a34de146cc159760df11c3',
    messagingSenderId: '6732882554',
    projectId: 'lamsa-app-ba17e',
    authDomain: 'lamsa-app-ba17e.firebaseapp.com',
    databaseURL: 'https://lamsa-app-ba17e-default-rtdb.firebaseio.com',
    storageBucket: 'lamsa-app-ba17e.firebasestorage.app',
    measurementId: 'G-B4HXR36YJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8XzLqQF6C-6B_z3qMISwI4R_cJ4fkIa0',
    appId: '1:6732882554:android:9276915c5e151689df11c3',
    messagingSenderId: '6732882554',
    projectId: 'lamsa-app-ba17e',
    databaseURL: 'https://lamsa-app-ba17e-default-rtdb.firebaseio.com',
    storageBucket: 'lamsa-app-ba17e.firebasestorage.app',
  );
}
